targets:
  $default:
    builders:
      figma_theme_generator|figma_theme_generator:
        enabled: true

builders:
  figma_theme_generator:
    target: ":figma_theme_generator"
    import: "package:figma_theme_generator/builder.dart"
    builder_factories: ["figmaThemeGenerator"]
    build_extensions: {".dart": [".figma_theme.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]