name: figma_theme_generator
description: Generate themes from Figma styles.
version: 0.1.7
homepage: https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  figma_theme: ^0.1.1
  recase: ^3.0.0
  analyzer: ^0.39.14
  code_builder: ^3.2.0
  build: ^1.0.0
  source_gen: ^0.9.7
  meta: ^1.1.8
  dart_style: ^1.3.6
  figma: ^2.0.2

  flutter:
    sdk: flutter
