name: figma_theme_generator
description: Generate themes from Figma styles.
version: 0.1.0
homepage: https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  figma_theme:
    path: ../figma_theme
  recase: ^3.0.0
  analyzer: ^0.39.17
  code_builder: ^3.2.0
  build: ^1.5.0
  source_gen: ^0.9.7
  meta: ^1.1.8
  dart_style:
  figma: #^1.0.3
    git: 
      url: https://github.com/aloisdeniel/figma
      ref: 9b3de4b7add173659da5dcf923556148bf0499dd

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
